In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data set Link:
https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset

In [2]:
data=pd.read_csv("loan_prediction.csv")
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

**Checking Last Five rows**

In [4]:
data.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
data.shape

(614, 13)

**Information about Data**

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

**Check Null Values**

In [7]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
data.isnull().sum()/len(data)*100

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

**Handling Missing Values**

In [9]:
data.drop('Loan_ID',axis=1,inplace=True)

In [10]:
columns=['Gender','Dependents','LoanAmount','Loan_Amount_Term']

In [11]:
data.dropna(subset=columns,inplace=True)

In [13]:
data.isnull().sum()/len(data)*100

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        5.424955
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [14]:
data['Self_Employed'].value_counts()

Self_Employed
No     451
Yes     72
Name: count, dtype: int64

In [15]:
data['Self_Employed']=data['Self_Employed'].fillna("No")

In [16]:
data.isnull().sum()/len(data)*100

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        0.000000
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [18]:
data["Credit_History"].mode()[0]

np.float64(1.0)

In [21]:
data['Credit_History']=data['Credit_History'].fillna(data["Credit_History"].mode()[0])

In [22]:
data.isnull().sum()/len(data)*100

Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
Loan_Status          0.0
Credit_Histor        0.0
dtype: float64

In [26]:
data.shape

(553, 12)

In [24]:
data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y

**handling Categorical Columns**

In [32]:
data.sample(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
71,Male,Yes,2,Not Graduate,Yes,1875,1875.0,97.0,360.0,1.0,Semiurban,Y
361,Male,Yes,2,Graduate,No,5000,3667.0,236.0,360.0,1.0,Semiurban,Y
231,Male,Yes,0,Graduate,No,3716,0.0,42.0,180.0,1.0,Rural,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
83,Male,Yes,0,Graduate,No,6000,2250.0,265.0,360.0,1.0,Semiurban,N

In [33]:
data['Dependents'].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [34]:
data['Dependents']=data['Dependents'].replace(to_replace='3+',value=4)

In [35]:
data['Dependents'].unique()

array(['1', '0', '2', 4], dtype=object)

In [38]:
print(data['Gender'].unique())
print(data['Married'].unique())
print(data['Loan_Status'].unique())
print(data['Education'].unique())

['Male' 'Female']
['Yes' 'No']
['N' 'Y']
['Graduate' 'Not Graduate']

In [39]:
data['Gender']=data['Gender'].map({'Male':1,'Female':0})

In [40]:
data['Married']=data['Married'].map({'Yes':1,'No':0})

In [42]:
data['Education'] = data['Education'].map({'Graduate':1,'Not Graduate':0}).astype('int')
data['Self_Employed'] = data['Self_Employed'].map({'Yes':1,'No':0}).astype('int')
data['Property_Area'] = data['Property_Area'].map({'Rural':0,'Semiurban':2,'Urban':1}).astype('int')
data['Loan_Status'] = data['Loan_Status'].map({'Y':1,'N':0}).astype('int')

In [43]:
print(data['Gender'].unique())
print(data['Married'].unique())
print(data['Loan_Status'].unique())
print(data['Education'].unique())

[1 0]
[1 0]
[0 1]
[1 0]

In [44]:
data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,1
5,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,1,1

In [45]:
X=data.drop(columns='Loan_Status',axis=1)
X

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1
5,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,1,0,2900,0.0,71.0,360.0,1.0,0
610,1,1,4,1,0,4106,0.0,40.0,180.0,1.0,0
611,1,1,1,1,0,8072,240.0,253.0,360.0,1.0,1
612,1,1,2,1,0,7583,0.0,187.0,360.0,1.0,1
613,0,0,0,1,1,4583,0.0,133.0,360.0,0.0,2

In [46]:
y=data['Loan_Status']
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 553, dtype: int64

**Feature Scaling**

In [48]:
data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,1
5,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,1,1

In [49]:
cols=['ApplicantIncome','CoapplicantIncome',	'LoanAmount',	'Loan_Amount_Term']

In [50]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X[cols]=scaler.fit_transform(X[cols])
X

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,1,1,1,0,-0.128694,-0.049699,-0.214368,0.279961,1.0,0
2,1,1,0,1,1,-0.394296,-0.545638,-0.952675,0.279961,1.0,1
3,1,1,0,0,0,-0.464262,0.229842,-0.309634,0.279961,1.0,1
4,1,0,0,1,0,0.109057,-0.545638,-0.059562,0.279961,1.0,1
5,1,1,2,1,1,0.011239,0.834309,1.440866,0.279961,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,1,0,-0.411075,-0.545638,-0.893134,0.279961,1.0,0
610,1,1,4,1,0,-0.208727,-0.545638,-1.262287,-2.468292,1.0,0
611,1,1,1,1,0,0.456706,-0.466709,1.274152,0.279961,1.0,1
612,1,1,2,1,0,0.374659,-0.545638,0.488213,0.279961,1.0,1
613,0,0,0,1,1,-0.128694,-0.545638,-0.154828,0.279961,0.0,2

**Splitting the dataset into training and testing set and applying K-fold cross validation**

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [61]:
model_df={}
def model_val(model,X,y):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(f"{model} accuracy is {accuracy_score(y_pred,y_test)}")

  score=cross_val_score(model,X,y,cv=5)
  print(f'{model} avg cross val score is{np.mean(score)}')

  model_df[model]=round(np.mean(score)*100,2)

In [63]:
model_df

{LogisticRegression(): np.float64(80.48)}

**Logistic Regression**

In [62]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model_val(model,X,y)

LogisticRegression() accuracy is 0.8018018018018018
LogisticRegression() avg cross val score is0.8047829647829647

**Support Vector Classifier**

In [64]:
from sklearn import svm
model=svm.SVC()
model_val(model,X,y)

SVC() accuracy is 0.7927927927927928
SVC() avg cross val score is0.7938902538902539

**Decision tree classifier**

In [65]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model_val(model,X,y)

DecisionTreeClassifier() accuracy is 0.7117117117117117
DecisionTreeClassifier() avg cross val score is0.7251597051597051

**random forest classifier**

In [66]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model_val(model,X,y)

RandomForestClassifier() accuracy is 0.7747747747747747
RandomForestClassifier() avg cross val score is0.7921048321048321

**Gradient Boosting Classifier**

In [67]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model_val(model,X,y)

GradientBoostingClassifier() accuracy is 0.7927927927927928
GradientBoostingClassifier() avg cross val score is0.7758067158067158

In [72]:
model_data = pd.DataFrame(list(model_df.items()), columns=['Model', 'Accuracy'])
model_data

                                               Model  Accuracy
0                               LogisticRegression()     80.48
1                                              SVC()     79.39
2                           DecisionTreeClassifier()     72.52
3  (DecisionTreeClassifier(max_features='sqrt', r...     79.21
4  ([DecisionTreeRegressor(criterion='friedman_ms...     77.58

**Hyperparameter tuning**

In [73]:
from sklearn.model_selection import RandomizedSearchCV

In [74]:
def hyperparameter(model,param_grid,X,y):
  random_search=RandomizedSearchCV(model,param_distributions=param_grid,n_iter=20,cv=5,random_state=42,
    n_jobs=-1)
  random_search.fit(X,y)
  print(f"best_score-: {random_search.best_score_}")
  print(f"best_params-: {random_search.best_params_}")

*Logistic Regression*

In [75]:

log_reg_grid={"C":np.logspace(-4,4,20),
             "solver":['liblinear']}
hyperparameter(LogisticRegression(),log_reg_grid,X,y)

best_score-: 0.8047829647829647
best_params-: {'solver': 'liblinear', 'C': np.float64(0.23357214690901212)}

**Random Forest**

In [78]:
rf_grid={'n_estimators':np.arange(10,1000,10),
  'max_features':['sqrt', 'log2'],
 'max_depth':[None,3,5,10,20,30],
 'min_samples_split':[2,5,20,50,100],
 'min_samples_leaf':[1,2,5,10]
 }
hyperparameter(RandomForestClassifier(),rf_grid,X,y)

best_score-: 0.8066011466011467
best_params-: {'n_estimators': np.int64(930), 'min_samples_split': 50, 'min_samples_leaf': 10, 'max_features': 'log2', 'max_depth': 30}